name: llama-triton-tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest -q
